services:
  - type: web
    name: face-confirmation
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_6mDK2ZfuOEXU@ep-purple-bonus-ac0zdopi-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: false
